### ISSUE TITLE
Different implementation

### ISSUE THREAD

**Issue by jm42** [badphp/logger#1]
Hey. I like the idea.

I was thinking about priorities such as [syslog](https://secure.php.net/manual/en/function.syslog.php) uses.

So I came with an alternative implementation that will accept the level as first argument:

``` php
$logger = logger("prod.log", LOG_ERR);

// This won't be logged
$logger(LOG_DEBUG, "The value %f should be %s", 123.1, '123');

// This will
$logger(LOG_CRIT, "The application is unavailable");
```

This way is more restrict as it has not a free condition. The condition is fixed that the given level should be lower than the one given when created. But restricting this is not big deal and it's preferred (in my opinion) to allow easy to use.

Now there is one function for all possible logging needs, which I like it more as I can pass it from one side to another as a single parameter.

Implementation can be found here: https://gist.github.com/jm42/ac120fbdb5379c5c0b36

**Comment by lloydzhou** [comment]
@jm42 
i alse have different implementation here (see #2 )
https://gist.github.com/lloydzhou/6a4e5f549905c4fa5e59

**Comment by noodlehaus** [comment]
thanks @jm42, @lloydzhou. i have a modified version that I use which behaves the same way, where we specify log levels (via syslog constants).

**Comment by noodlehaus** [comment]
i've updated the repo. thanks for raising this, @jm42.
