### ISSUE TITLE
using fwrite instead of error_log

### ISSUE THREAD

**Issue by lloydzhou** [badphp/logger#2]
i like this simple library.

but there's some issue:
1. every time to write log will call error_log.
2. only work fine for php5.6 

i have write another implementation on gist: https://gist.github.com/lloydzhou/6a4e5f549905c4fa5e59
1. using register_shutdown_function only open file once.
2. keep you syntax.
3. reduce some code.

**Comment by noodlehaus** [comment]
you're correct. i started experiencing this last night, after getting with PHP7.

this had a version which used `fwrite` but i had problems with concurrency, where overlapping writes ruined the file. the modified version i have right now uses `file_put_contents` with the `FILE_APPEND|LOCK_EX` flags.

i'll be updating this in a bit.

**Comment by lloydzhou** [comment]
@noodlehaus 
i have update the gist, to using file_put_contents :smiling_imp: 
also using current instead of array_shift.

**Comment by noodlehaus** [comment]
have updated the repo. thanks for raising this @lloydzhou.
